version: "3.9"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Password"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql

  order-service:
    build:
      context: .
      dockerfile: ./OrderService.Api/Dockerfile
    container_name: OrderService
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Database=OrderDb;User Id=sa;Password=YourStrong!Password;TrustServerCertificate=True;"
    depends_on:
      - db

volumes:
  sqlserver_data:
