name: Docker Tag and Push - Order Service

on:
  push:
    branches:
      - main

jobs:
  tag-and-push:
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.ORDERSERVICE_SECRET }}

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: |
          IMAGE_NAME="evis92/order-service"
          docker build -t $IMAGE_NAME:latest -f ./OrderService.Api/Dockerfile .

      # Step 5: Push Docker Image to Registry
      - name: Push Docker Image
        run: |
          IMAGE_NAME="evis92/order-service"
          docker push $IMAGE_NAME:latest
